site_name: Data science API

nav:
  - Index: index.md
  - User Documentation:
    - Basic requests: get-requests.md
    - Pipelines: Execute-pipeline.md
    - operations: operations_info.md
    - connections: connections_info.md
    - list of operations:
      - load: operations/load_operation.md
      - select_columns: operations/select_columns_operation.md
      - filter_rows: operations/filter_rows_operation.md
      - merge: operations/merge_operation.md
      - duplicate: operations/duplicate_operation.md
      - decision_tree: operations/decision_tree.md
      - predict: operations/predict_operation.md
    
  - Developer Documentation:
    - devdocs: under-construction.md
